name: Lint and Test

on: push

jobs:
  clj_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cljstyle: 0.15.0
      - run: cljstyle check --report -v

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 17, 21]
    name: Test (Java ${{ matrix.java }})
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          java-package: jdk
          architecture: x64
          distribution: 'zulu'

      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2
          key: clj-cache-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            clj-cache-

      - name: Run tests
        run: clojure -M:dev:test

