name: Lint and Test

on: push

jobs:
  clj_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 0918nobita/setup-cljstyle@v0.2.0
        with:
          cljstyle-version: 0.14.0
      - run: cljstyle check --report -v

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 15]
    name: Test (Java ${{ matrix.java }})
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          java-package: jdk
          architecture: x64
          distribution: 'zulu'

      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest

      - name: Cache dependencies
        uses: toyokumo/cache@main
        with:
          path: |
            ~/.m2
          key: clj-cache-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            clj-cache-

      - name: Run tests
        run: clojure -M:dev:test

